from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Column, Integer, String, DateTime
from sqlalchemy.orm import sessionmaker, scoped_session
from sqlalchemy.orm import relationship, backref
import os

db_url = os.environ.get("DATABASE_URL", "sqlite:///txtmnky.db")

ENGINE = create_engine("sqlite:///txtmnky.db", echo=False) 
# signified current directory

session = scoped_session(sessionmaker(bind=ENGINE, autocommit = False, autoflush = False))
    # ENGINE: here is how to connect
    # ORM:  generate SQL for you
    # echo: print out what was generated by ORM; good for debugging

#Base is a class defined in SQLAlchemy
Base = declarative_base()
Base.query = session.query_property()

class Survey(Base):
    __tablename__ = "surveys"
    id = Column(Integer, primary_key = True)
    twilio_owner_id = Column(Integer, nullable=False)
    question = Column(String(140), nullable=False)
    creation_date = Column(DateTime, nullable=True)

    def __init__(self, id= None, twilio_owner_id  = None, question = None, creation_date = None):
    	self.id = id
    	self.twilio_owner_id = owner_id
    	self.question = question
        self.creation_date = creation_date

class SurveyRespondent(Base):
    __tablename__ = "survey_respondents"
    respondent_number = Column(String, primary_key = True) 
    survey_id = Column(Integer, nullable=False)

    def __init__(self, respondent_number= None, survey_id  = None):
    	self.respondent_number = respondent_number
    	self.survey_id = survey_id

class SurveyResponse(Base):
    __tablename__ = "survey_responses"
    id = Column(Integer, primary_key = True)
    survey_id = Column(Integer, nullable=False)
    respondent_number = Column(String, nullable=False)
    response = Column(String(140), nullable=False)

    

def create_db():
    Base.metadata.create_all(ENGINE)

def main():
   pass
  
if __name__ == "__main__":
   main()
